### PR TITLE
Waiting on #31: DC mapit postcode lookup

### PR DESCRIPTION
**Pull request by symroe**
Spotted while working on #31, we should try a couple of different MapIt installs seeing as we have them.

### CODE REVIEW

**Comment by symroe** [comment]
Also, based off #31, so that need merging first.

**Comment by chris48s** [comment]
Will have a look once its rebased onto master. That should sort the `multiple leaf nodes in the migration graph` failures

**Comment by chris48s** [comment]
If you're in the mood for feedback, ideally I would probably define `BaseMaPitPostcodeLookup` as an abstract class and declare `mapit_base` as an abstract property.

If you're trying to do a million other things, just slap it in there and we can worry about it another day :)

**Comment by symroe** [comment]
I choose the blue pill!

**Pull request merged**
