### PR TITLE
Add Election ID Documentation

### LINKED ISSUE #48: Update reference definition
Update https://democracyclub.org.uk/projects/election-ids/reference/ to reflect current id creation rules

### PR DESCRIPTION
**Pull request by chris48s**
Notes:
* This is a useful starting point. It probably needs refinement, but it is a step up from nothing.
* I've ~fixed 'Election Types'~ made 'Election Types' less broken in this PR, but I'm not sure if it is necessarily a useful thing to have alongside this as a lot of the content is duplicated. Maybe it should just be replaced by this?
* I'm struggling to properly articulate when the organisation layer is relevant. An organisation is 'an administrative body which can hold an election', but sometimes that organisation is implicit in the election type and sometimes it needs to be explicit in the identifier but I can't quite explain the rule for when each of those scenarios is true.
* ~I have deliberately not talked about how you know what area names to use because this is still a bit.. fuzzy.~
* ~I've also left out a description of the slugging algortihm. I'm not quite sure how to address it.~
* I need to submit another PR to https://github.com/DemocracyClub/Website/ removing https://github.com/DemocracyClub/Website/blob/master/democracy_club/templates/election-ids/reference.html and linking to this.

Closes #48

### CODE REVIEW

**Comment by chris48s** [comment]
[Every Election: New reference definition](https://trello.com/c/AIwLI4a3/927-every-election-new-reference-definition)

**Comment by chris48s** [comment]
4a5e396 adds some more detail on a couple of points. Can we see if we can come up with a sentence on Monday to try and explain when the organisation layer is/isn't relevant. I think both of us are fairly keen to get some better docs for this live 📚

**Comment by symroe** [comment]
> An administrative body which can hold an election.

"When am election type can only contain a single organisation the organisation part of the ID is excluded. This is to prevent `parl.parl` where the type and the organisation are both `parl`."

Is that the only case, actually?

**Comment by chris48s** [comment]
`naw`, `sp`, `gla` are the same, but that makese sense - cheers

**Pull request merged**
